name: simple_dart_logger
description: A simple yet extensible logger package written purely in dart. 
  It is purposefully platform agnostic.
version: 1.2.1
repository: https://github.com/MyLittlePenguin/simple_dart_logger

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
